### PR TITLE
feat: add new change reason kind MIGRATION

### LINKED ISSUE #111: Extend StateChangeReasonKind with new reason Migration
This changes on nearcore https://github.com/near/nearcore/commit/473e71b5127e3795719c793ab727ef629de53d33 have introduced a new variant to the enum which we are not handling. We need to add it along with corresponding migrations into database schema and models.

### PR DESCRIPTION
**Pull request by telezhnaya**
Fixes #111

### CODE REVIEW

**Review by khorolets — CHANGES_REQUESTED** [review]
It's great, but also we need to extend corresponding enum and adjust it's impl :)

https://github.com/near/near-indexer-for-explorer/blob/master/src/models/enums.rs#L103-L129

Also I expect tests to fail after you made this change, because it's in newer commit than release one, so you can take latest master commit for now, we will include it in later release

**Comment by telezhnaya** [comment]
> It's great, but also we need to extend corresponding enum and adjust it's impl :)

I am sorry for that 😞 I forgot to search for ids in camelCase in the project.

> Also I expect tests to fail after you made this change, because it's in newer commit than release one, so you can take latest master commit for now, we will include it in later release

Don't worry about that. If we merge this one earlier, I will rebase the release commit, so the order will be OK.

**Comment by khorolets** [comment]
>Don't worry about that. If we merge this one earlier, I will rebase the release commit, so the order will be OK.

We will postpone merging, will create a release based on #120 and after that will merge this, because this is a preparation to `1.20.0` nearcore release.

**Review by khorolets — APPROVED** [review]
Nice and easy! Thank you!

**Comment by khorolets** [comment]
@telezhnaya could you please run `cargo fmt`?

**Comment by telezhnaya** [comment]
> could you please run cargo fmt?

@khorolets  It finished silently with no editions, code is clean 👌

**Comment by khorolets** [comment]
>  It finished silently with no editions, code is clean 👌

my bad, I've misread the build error, sorry :)

**Review by frol — APPROVED** [review]

**Pull request merged**
